

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Company" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying,
    "sme" character varying,
    "sme_email" character varying,
    "techs" character varying
);


ALTER TABLE "public"."Company" OWNER TO "postgres";


ALTER TABLE "public"."Company" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Company_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."dev_bug_tracker" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "app _name" character varying,
    "submitter_name" character varying,
    "submitter_email" character varying,
    "expected_behavior" character varying,
    "actual_behavior" character varying,
    "date_submitted" character varying,
    "title" character varying,
    "status" character varying
);


ALTER TABLE "public"."dev_bug_tracker" OWNER TO "postgres";


ALTER TABLE "public"."dev_bug_tracker" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Dev Team Bug Tracker_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."escalated_tickets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "gc_name" character varying,
    "deadline" timestamp without time zone,
    "description" character varying,
    "tech" character varying,
    "ticket" character varying,
    "status" character varying NOT NULL,
    "tech_email" character varying,
    "ticked_in_cw" boolean,
    "escalation_type" character varying,
    "urgency" character varying,
    "created_gc_id" character varying,
    "time_submitted" timestamp without time zone,
    "close_date" timestamp without time zone,
    "comp_name" character varying,
    "hoz_team" character varying,
    "title" character varying,
    "review" character varying,
    "submitted_datetime_txt" "text",
    "escalation_level" smallint,
    "messageid" character varying
);


ALTER TABLE "public"."escalated_tickets" OWNER TO "postgres";


COMMENT ON TABLE "public"."escalated_tickets" IS 'All records of scalated tickets';



ALTER TABLE "public"."escalated_tickets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Escalated Tickets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."HozTeam" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying,
    "description" character varying,
    "team_owner_email" character varying,
    "member_email" character varying,
    "team_owner" character varying,
    "members" character varying
);


ALTER TABLE "public"."HozTeam" OWNER TO "postgres";


ALTER TABLE "public"."HozTeam" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."HozTeam_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."escalation_activity_log" (
    "id" integer NOT NULL,
    "full_name" "text" NOT NULL,
    "email_address" "text" NOT NULL,
    "total_responses" integer DEFAULT 0 NOT NULL,
    "total_escalations_created" integer DEFAULT 0,
    "escalation_participated" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."escalation_activity_log" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."escalation_activity_log_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."escalation_activity_log_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."escalation_activity_log_id_seq" OWNED BY "public"."escalation_activity_log"."id";



CREATE TABLE IF NOT EXISTS "public"."escalation_responses" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "suggested_solution" "text",
    "responder_name" "text",
    "responder_email" "text",
    "created_date" timestamp with time zone DEFAULT "now"(),
    "subject" character varying NOT NULL,
    "response_time" timestamp without time zone,
    "response_time_txt" "text"
);


ALTER TABLE "public"."escalation_responses" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."flow_error_logs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "flow_name" "text",
    "run_id" "text",
    "step_name" "text",
    "error_message" "text",
    "error_code" "text",
    "item_context" "text",
    "trigger_time" "text",
    "logged_at" "text",
    "environment" "text",
    "flow_status" "text"
);


ALTER TABLE "public"."flow_error_logs" OWNER TO "postgres";


COMMENT ON TABLE "public"."flow_error_logs" IS 'The flow_error_logs table records all error events generated during the execution of Power Automate flows. Each entry represents an individual failure, typically associated with a specific step within a flow loop or critical stage. It captures contextual information like the flow name, run ID, step name, error message, error code, relevant metadata, and timestamps.';



ALTER TABLE "public"."flow_error_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."flow_error_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."from_sharepoint" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "gc_name" character varying,
    "deadline" timestamp without time zone,
    "description" character varying,
    "tech" character varying,
    "ticket" character varying,
    "status" character varying NOT NULL,
    "tech_email" character varying,
    "ticked_in_cw" boolean,
    "escalation_type" character varying,
    "urgency" character varying,
    "comp_id" bigint,
    "hoz-id" bigint,
    "created_gc_id" character varying,
    "time_submitted" timestamp without time zone,
    "close_date" timestamp without time zone,
    "comp_name" character varying,
    "hoz_team" character varying,
    "title" character varying,
    "review" character varying
);


ALTER TABLE "public"."from_sharepoint" OWNER TO "postgres";


COMMENT ON TABLE "public"."from_sharepoint" IS 'This is a duplicate of escalated_tickets';



ALTER TABLE "public"."from_sharepoint" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."from_sharepoint_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."incident_reports" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "date_entered" timestamp without time zone NOT NULL,
    "status" "text" NOT NULL,
    "ticket" bigint NOT NULL,
    "board" "text" NOT NULL,
    "age" integer NOT NULL,
    "company" "text" NOT NULL,
    "summary" "text" NOT NULL,
    "tech" "text" NOT NULL,
    "contact" "text",
    "recurrence_count" integer DEFAULT 1 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"())
);


ALTER TABLE "public"."incident_reports" OWNER TO "postgres";


ALTER TABLE ONLY "public"."escalation_activity_log" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."escalation_activity_log_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."Company"
    ADD CONSTRAINT "Company_Title_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."Company"
    ADD CONSTRAINT "Company_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."Company"
    ADD CONSTRAINT "Company_id_key1" UNIQUE ("id");



ALTER TABLE ONLY "public"."Company"
    ADD CONSTRAINT "Company_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."dev_bug_tracker"
    ADD CONSTRAINT "Dev Team Bug Tracker_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."escalated_tickets"
    ADD CONSTRAINT "Escalated Tickets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."HozTeam"
    ADD CONSTRAINT "HozTeam_Title_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."HozTeam"
    ADD CONSTRAINT "HozTeam_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."HozTeam"
    ADD CONSTRAINT "HozTeam_id_key1" UNIQUE ("id");



ALTER TABLE ONLY "public"."HozTeam"
    ADD CONSTRAINT "HozTeam_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."escalated_tickets"
    ADD CONSTRAINT "escalated_tickets_gc_name_key" UNIQUE ("gc_name");



ALTER TABLE ONLY "public"."escalated_tickets"
    ADD CONSTRAINT "escalated_tickets_ticket_key" UNIQUE ("ticket");



ALTER TABLE ONLY "public"."escalation_activity_log"
    ADD CONSTRAINT "escalation_activity_log_email_address_key" UNIQUE ("email_address");



ALTER TABLE ONLY "public"."escalation_activity_log"
    ADD CONSTRAINT "escalation_activity_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."escalation_responses"
    ADD CONSTRAINT "escalation_responses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."flow_error_logs"
    ADD CONSTRAINT "flow_error_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."from_sharepoint"
    ADD CONSTRAINT "from_sharepoint_gc_name_key" UNIQUE ("gc_name");



ALTER TABLE ONLY "public"."from_sharepoint"
    ADD CONSTRAINT "from_sharepoint_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."incident_reports"
    ADD CONSTRAINT "incident_reports_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."incident_reports"
    ADD CONSTRAINT "incident_reports_ticket_key" UNIQUE ("ticket");



ALTER TABLE ONLY "public"."escalated_tickets"
    ADD CONSTRAINT "Escalated Tickets_comp_name_fkey" FOREIGN KEY ("comp_name") REFERENCES "public"."Company"("title");



ALTER TABLE ONLY "public"."escalated_tickets"
    ADD CONSTRAINT "Escalated Tickets_hoz_team_fkey" FOREIGN KEY ("hoz_team") REFERENCES "public"."HozTeam"("title");



ALTER TABLE ONLY "public"."escalation_responses"
    ADD CONSTRAINT "escalation_responses_subject_fkey" FOREIGN KEY ("subject") REFERENCES "public"."escalated_tickets"("gc_name");



ALTER TABLE ONLY "public"."from_sharepoint"
    ADD CONSTRAINT "from_sharepoint_comp_id_fkey" FOREIGN KEY ("comp_id") REFERENCES "public"."Company"("id");



ALTER TABLE ONLY "public"."from_sharepoint"
    ADD CONSTRAINT "from_sharepoint_comp_name_fkey" FOREIGN KEY ("comp_name") REFERENCES "public"."Company"("title");



ALTER TABLE ONLY "public"."from_sharepoint"
    ADD CONSTRAINT "from_sharepoint_hoz-id_fkey" FOREIGN KEY ("hoz-id") REFERENCES "public"."HozTeam"("id");



-- ALTER TABLE ONLY "public"."from_sharepoint"
--     ADD CONSTRAINT "from_sharepoint_hoz_team_fkey" FOREIGN KEY ("hoz_team") REFERENCES "public"."HozTeam"("title");

ALTER TABLE ONLY "public"."from_sharepoint"
    ADD CONSTRAINT "from_sharepoint_hoz_team_fkey" FOREIGN KEY ("hoz_team") REFERENCES "public"."HozTeam"("title");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."Company" TO "anon";
GRANT ALL ON TABLE "public"."Company" TO "authenticated";
GRANT ALL ON TABLE "public"."Company" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Company_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Company_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Company_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."dev_bug_tracker" TO "anon";
GRANT ALL ON TABLE "public"."dev_bug_tracker" TO "authenticated";
GRANT ALL ON TABLE "public"."dev_bug_tracker" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Dev Team Bug Tracker_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Dev Team Bug Tracker_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Dev Team Bug Tracker_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."escalated_tickets" TO "anon";
GRANT ALL ON TABLE "public"."escalated_tickets" TO "authenticated";
GRANT ALL ON TABLE "public"."escalated_tickets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Escalated Tickets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Escalated Tickets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Escalated Tickets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."HozTeam" TO "anon";
GRANT ALL ON TABLE "public"."HozTeam" TO "authenticated";
GRANT ALL ON TABLE "public"."HozTeam" TO "service_role";



GRANT ALL ON SEQUENCE "public"."HozTeam_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."HozTeam_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."HozTeam_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."escalation_activity_log" TO "anon";
GRANT ALL ON TABLE "public"."escalation_activity_log" TO "authenticated";
GRANT ALL ON TABLE "public"."escalation_activity_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."escalation_activity_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."escalation_activity_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."escalation_activity_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."escalation_responses" TO "anon";
GRANT ALL ON TABLE "public"."escalation_responses" TO "authenticated";
GRANT ALL ON TABLE "public"."escalation_responses" TO "service_role";



GRANT ALL ON TABLE "public"."flow_error_logs" TO "anon";
GRANT ALL ON TABLE "public"."flow_error_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."flow_error_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."flow_error_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."flow_error_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."flow_error_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."from_sharepoint" TO "anon";
GRANT ALL ON TABLE "public"."from_sharepoint" TO "authenticated";
GRANT ALL ON TABLE "public"."from_sharepoint" TO "service_role";



GRANT ALL ON SEQUENCE "public"."from_sharepoint_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."from_sharepoint_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."from_sharepoint_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."incident_reports" TO "anon";
GRANT ALL ON TABLE "public"."incident_reports" TO "authenticated";
GRANT ALL ON TABLE "public"."incident_reports" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
